#!/usr/bin/env zsh

DIR=`dirname $0`
CMD=`basename $0`
{ test -r $DIR } || {
    echo "error: launch webnomad commands from your project directory"
    echo "i.e: ./$DIR/$CMD"
    return 1
}

source ${DIR}/utils

{ test -r config.zsh } || {
    error "Directory not configured for WebNomad. First use ./webnomad/init"
    exit 1 }

source config.zsh

notice "Rendering $BRAND website"
act "Title: $TITLE"


source ${DIR}/render source

# Main

mkdir -p test
# render all HTML views
htmls=(`find views -type f -name '*.html'`)
for src in $htmls; do
    # read meta commands
    cat ${src} | read_meta

    # compute destination file
    dst="test/`basename ${src%.*}`$EXTENSION"

    render_header > $dst

    # close <head> as nothing else is needed
    cat <<EOF >> $dst

<link rel="stylesheet" href="css/jquery.sidr.dark.css">

</head> <!-- end of <head> -->

<body>
  <div class="container">
EOF

    # navbar
    cat tmpl/navbar.html >> $dst

    # start the body of article
    cat <<EOF >> $dst
<p>&nbsp;</p>
<a id="menu" href="#sidr">Design test</a>

<article>
EOF

    # render html
    act -n "Html rendering: $dst "
    cat $src | render_html >> $dst

cat <<EOF >> $dst
</article>
<p>&nbsp;</p>

<script type="text/javascript" src="js/jquery.min.js"></script>
<script type="text/javascript" src="js/jquery.sidr.js"></script>

 
<div id="sidr">
  <h2>Design test</h2>
  <h3>Font size</h3>
  <ul>
    <li><a href="#" id="smaller">smaller</a><li><a href="#" id="bigger">bigger</a></li>
  </ul>

  <h3>Font family</h3>
<select id="headerfamily" name="header font family">
<option value="Arial">Arial</option>
<option value="Courier">Courier</option>
</select>

</div>

<script>
\$(document).ready(function() {
  \$('#menu').sidr({
     name: 'sidr',
     side: 'right',
     displace: false
});
});
\$('#h1size').change(function() { \$('h1').css('font-size', \$('#h1size').val() + "em" ); })
\$('#headerfamily').change(function(){ \$('h1').css('font-family', \$('#headerfamily').val() ); })
</script>

EOF

    render_footer >> $dst

    act "done"

done


for m in `find views -mindepth 1 -type d `; do
    act -n "publishing $m... "
    rsync -r $m test/
    print "done"
done

# add design test libs
mkdir -p test/js
cp $DIR/js/jquery.min.js test/js
cp $DIR/js/jquery.sidr.js test/js
cp $DIR/css/jquery.sidr.dark.css test/css
