#!/usr/bin/env zsh
#
# Jaro Web, your slick and static website publisher
#
# Copyleft (C) 2012 Denis Roio <jaromil@dyne.org>
#
# This source  code is free  software; you can redistribute  it and/or
# modify it under the terms of  the GNU Public License as published by
# the Free  Software Foundation; either  version 3 of the  License, or
# (at your option) any later version.
#
# This source code is distributed in  the hope that it will be useful,
# but  WITHOUT ANY  WARRANTY;  without even  the  implied warranty  of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# Please refer to the GNU Public License for more details.
#
# You should have received a copy of the GNU Public License along with
# this source code; if not, write to:
# Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

source jaroweb/utils

{ test -r config.zsh } || {
    error "Directory not configured for Jaro Web. First use jaroweb init"
    exit 1 }


####################################

{ test -z $1 } && {
  notice "List of available themes:"
  for i in `ls jaroweb/themes`; do
      act "$i"
  done
  exit 0
}

{ test -r jaroweb/themes/$1 } || {
    error "Theme not found: $1"
    exit 1
}

notice "Installing theme: $1"
cp jaroweb/themes/$1/bootstrap.min.css \
    views/css/bootstrap.min.css
exit 0
